<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>4rVivi.OcrServer</AssemblyName>
    <RootNamespace>FourRVivi.OcrServer</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RapidOcrNet\RapidOcrNet.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\RapidOcrNet\models\v5\**">
      <Link>models\v5\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
